config/routes.rb
# Student constraint
class StudentConstraint
  def matches?(request)
    u = User.find(request.session['warden.user.user.key'][0])
    u[0].usertype == 1 || 2 || 3
  end
end

# Teacher constraint
class TeacherConstraint
  def matches?(request)
    u = User.find(request.session['warden.user.user.key'][0])
    u[0].usertype == 2 || 1 || 3
  end
end

# Admin constraint
class AdminConstraint
  def matches?(request)
    u = User.find(request.session['warden.user.user.key'][0])
    u[0].usertype == 3 || 2 || 1
  end
end

Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    namespace :student, constraints: StudentConstraint.new do
      root 'dashboard#index'
      resources :competencies do
        resources :learning_objectives do
          resources :activities do
            resources :contexts
            resources :proofs
          end
        end
      end
    end

    namespace :teacher, constraints: TeacherConstraint.new do
      root 'dashboard#index'
      resources :user
      get 'students' => 'user#students'
      get 'teachers' => 'user#teachers'
    end

    namespace :admin, constraints: AdminConstraint.new do
      root 'dashboard#index'
      resources :competencies
      resources :user
    end
  end

  root 'pages#root'
  get 'home/index'
end

app/models/activity.rb
# Model class Activity
class Activity < ActiveRecord::Base
  belongs_to :learning_objective
  has_many :proofs
  has_one :context
end

app/models/competency.rb
# Model class Competency
class Competency < ActiveRecord::Base
  has_many :learning_objectives
  has_many :feedbacks, through: :competency_feedbacks
  has_many :competency_feedbacks

  accepts_nested_attributes_for :feedbacks, :competency_feedbacks
end

app/models/competency_feedback.rb
# competency feedback class
class CompetencyFeedback < ActiveRecord::Base
  belongs_to :competency
  belongs_to :feedback
end

app/models/context.rb
# context model class
class Context < ActiveRecord::Base
  has_one :activity
end

app/models/feedback.rb
# Model class Feedback
class Feedback < ActiveRecord::Base
  belongs_to :user
  belongs_to :student, class_name: User, foreign_key: :student_id
  belongs_to :learning_objective
  has_many :competencies, through: :competency_feedbacks
  has_many :competency_feedbacks

  accepts_nested_attributes_for :competencies, :competency_feedbacks
end

app/models/learning_objective.rb
# learningobjective class
class LearningObjective < ActiveRecord::Base
  has_many :activities
  has_many :feedbacks
  belongs_to :user
  belongs_to :competency
end

app/models/proof.rb
# Model class Proof
class Proof < ActiveRecord::Base
  belongs_to :activity
end

app/models/user.rb
# user class
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # relations
  has_many :feedbacks
  has_many :student_feedbacks, class_name: Feedback, foreign_key: :student_id
  has_many :learning_objectives
end

app/controllers/admin/competencies_controller.rb
# class competencies controller
class Admin::CompetenciesController < ApplicationController
  def index
    @competency = Competency.all
  end

  def show
    @competency = Competency.find(params[:id])
  end

  def new
    @competency = Competency.new
  end

  def create
    @competency = Competency.new(competency_params)

    if @competency.save
      redirect_to admin_competencies_path, notice:
                                              'Competentie succesvol aangemaakt'
    else
      render 'new'
    end
  end

  def edit
    @competency = Competency.find(params[:id])
  end

  def update
    @competency = Competency.find(params[:id])

    if @competency.update(competency_params)

      redirect_to admin_competencies_path, notice:
                                              'Competentie succesvol aangepast'

    else
      render 'edit'
    end
  end

  def destroy
    @competency = Competency.find(params[:id])
    @competency.destroy
    redirect_to admin_competencies_path, notice:
                                              'Competentie succesvol verwijderd'
  end

  private

  def competency_params
    params.require(:competency)
      .permit(:name, :description, :active)
  end
end

app/controllers/application_controller.rb
# applicationcontroller class
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
# home comtroller class
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
# pages controller
class PagesController < ApplicationController
  def root
    if user_signed_in?
      # check user type
      usertype = current_user.usertype
      case usertype
      when 1
        redirect_to student_root_path
      when 2
        redirect_to student_root_path
      when 3
        redirect_to admin_root_path
      end
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/student/competencies_controller.rb
# class competency
class Student::CompetenciesController < ApplicationController
end

app/helpers/admin/competencies_helper.rb
# competencie helper
module Admin::CompetenciesHelper
end

app/helpers/admin/dashboard_helper.rb
# dashboard helper
module Admin::DashboardHelper
end

app/helpers/admin/user_helper.rb
# user helper
module Admin::UserHelper
end

app/helpers/application_helper.rb
# application helper
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/home_helper.rb
# homehelper
module HomeHelper
end

app/helpers/pages_helper.rb
# pages helper
module PagesHelper
end

app/helpers/student/competencies_helper.rb
# competency helper
module Student::CompetenciesHelper
end

app/helpers/student/contexts_helper.rb
# context helper
module Student::ContextsHelper
end

app/helpers/student/dashboard_helper.rb
# dashboard helper
module Student::DashboardHelper
end

app/helpers/student/proofs_helper.rb
# proofs helper
module Student::ProofsHelper
end

app/helpers/teacher/dashboard_helper.rb
# dashboard helper
module Teacher::DashboardHelper
end

app/helpers/teacher/user_helper.rb
# user helper
module Teacher::UserHelper
end

app/views/admin/competencies/_form.html.haml
.caution
  %p (!) Bij het aanmaken of aanpassen van een competentie geldt dat de naam van een competentie maximaal 30 karakters mag bevatten. Voor de omschrijving van de competentie geldt een maximum van 35 karakters.

= form_for [:admin, @competency] do |co|
  .dev
    = co.label 'Naam competentie'
    .sub
      = co.text_area :name, :id => "message_box"
  .dev
    = co.label 'Omschrijving Competentie'
    .sub
      = co.text_area :description, :id => "message_area"
  .dev
    = co.label 'Is de competentie actief?'
    .sub
    
      = co.check_box :active, as: :boolean 

  .under
    = co.submit 'Bevestig', :class => 'submit_button' 

app/views/admin/competencies/edit.html.haml
#sections
	%h2 Competentie aanpassen
	= render 'form'
	.under
		= link_to 'Terug naar alle competenties', admin_competencies_path

app/views/admin/competencies/index.html.haml
#sections
  %h2 Overzicht van competenties 

  - @competency.each do |co|
     
    %li{class: "#{calculate_color(co.name)} competenties"}
      %h2.name= co.name
      .inside_block_up
        = co.description 
      .inside_block_mid 
        Actief:
        = co.active
      .inside_block_down
        = link_to 'Aanpassen', edit_admin_competency_path(co) 
        |
        = link_to 'Verwijderen', admin_competency_path(co), method: :delete, data: { confirm: 'Weet je het zeker?'}

  .under
    = link_to '+ Nieuwe competentie', new_admin_competency_path
    |
    = link_to 'Terug naar het Dashboard', admin_root_path

app/views/admin/competencies/new.html.haml
#sections
	%h2 Een nieuwe competentie aanmaken
	= render 'form'
	.under
		= link_to 'Terug naar Dashboard', admin_root_path

app/views/admin/competencies/show.html.haml
#sections 
	
	