config/routes.rb
# Student constraint
class StudentConstraint
  def matches?(request)
    u = User.find(request.session['warden.user.user.key'][0])
    u[0].usertype == 1 || 2 || 3
  end
end

# Teacher constraint
class TeacherConstraint
  def matches?(request)
    u = User.find(request.session['warden.user.user.key'][0])
    u[0].usertype == 2 || 1 || 3
  end
end

# Admin constraint
class AdminConstraint
  def matches?(request)
    u = User.find(request.session['warden.user.user.key'][0])
    u[0].usertype == 3 || 2 || 1
  end
end

Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    namespace :student, constraints: StudentConstraint.new do
      root 'dashboard#index'
      resources :competencies do
        resources :learning_objectives do
          resources :activities do
            resources :contexts
            resources :proofs
          end
        end
      end
    end

    namespace :teacher, constraints: TeacherConstraint.new do
      root 'dashboard#index'
      resources :user
      get 'students' => 'user#students'
      get 'teachers' => 'user#teachers'
    end

    namespace :admin, constraints: AdminConstraint.new do
      root 'dashboard#index'
      resources :competencies
      resources :user
    end
  end

  root 'pages#root'
  get 'home/index'
end

app/models/proof.rb
# Model class Proof
class Proof < ActiveRecord::Base
  belongs_to :activity
end

app/controllers/student/activities_controller.rb
# class activity
class Student::ActivitiesController < ApplicationController
  def index
    @activity = LearningObjective.find(
      params[:learning_objective_id]).activities.all
  end

  def show
    @activity = Activity.find(params[:id])
    @context = Context.where(activity_id: @activity).first
    if @context.nil?
      @co = 'Er moet nog een context worden toegevoegd'
    else
      @co = @context.description
    end
  end

  def new
    @activity = Activity.new
  end

  def create
    learning_objective = LearningObjective.find(params[:learning_objective_id])
    @activity = LearningObjective.find(learning_objective).activities.new(
      activity_params)

    if @activity.save
      redirect_to student_competency_learning_objective_activities_path, notice:
       'Activiteit succesvol aangemaakt'
    else
      render 'new'
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])

    if @activity.update(activity_params)
      redirect_to student_competency_learning_objective_activities_path, notice:
       'Activiteit succesvol aangepast'
    else
      render 'edit'
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to student_competency_learning_objective_activities_path, notice:
     'Activiteit succesvol verwijderd'
  end

  private

  def activity_params
    params.require(:activity)
      .permit(:description, :learning_objective_id)
  end
end

app/controllers/student/competencies_controller.rb
# class competency
class Student::CompetenciesController < ApplicationController
end

app/controllers/student/contexts_controller.rb
class Student::ContextsController < ApplicationController

  def index 

    
  def new
    @context = Context.new
  end

  def create
    @context = Context.new(context_params)

    if @context.save
      @context.activity_id = params[:activity_id]
      @context.save
      redirect_to student_competency_learning_objective_activity_path(params[:competency_id], params[:learning_objective_id], params[:activity_id]), notice:  'Context succesvol toegevoegd!'
    else
      render 'new'
    end
  end

  def edit
    @context = Context.find(params[:id])
  end

  def update
    @context = Context.find(params[:id])

    if @context.update(context_params)
      redirect_to student_competency_learning_objective_activity_path(params[:competency_id], params[:learning_objective_id], params[:activity_id]), notice: 'Context succesvol aangepast'
    else
      render 'edit'
    end
  end

  def destroy
    @context = Context.find(params[:id])
    @context.destroy
    redirect_to student_competency_learning_objective_activity_path(params[:competency_id], params[:learning_objective_id], params[:activity_id]), notice: 'Activiteit succesvol verwijderd'
  end

  private

  def context_params
    params.require(:context).permit(:description)
  end
end

app/controllers/student/dashboard_controller.rb
# class dashboard
class Student::DashboardController < ApplicationController
  def index
    @competency = Competency.where(active: true).all
  end
end

app/controllers/student/learning_objectives_controller.rb
# class learning objective
class Student::LearningObjectivesController < ApplicationController
  def index
    @competency = params[:competency_id]
    @learning_objectives = LearningObjective.where(user_id: current_user.id,
                                                   competency_id: @competency)
  end

  def show
    @learning_objective = LearningObjective.find(params[:id])
  end

  def new
    @learning_objective = LearningObjective.new
  end

  def create
    @learning_objective = LearningObjective.new(learning_objective_params)
    @learning_objective.user_id = current_user.id

    if @learning_objective.save
      redirect_to student_competency_learning_objectives_path, notice:
       'Leerdoel succesvol aangemaakt'
    else
      render 'new'
    end
  end

  def edit
    @learning_objective = LearningObjective.find(params[:id])
  end

  def update
    @learning_objective = LearningObjective.find(params[:id])

    if @learning_objective.update(learning_objective_params)

      redirect_to student_competency_learning_objectives_path, notice:
       'Leerdoel succesvol aangepast'

    else
      render 'edit'
    end
  end

  def destroy
    @learning_objective = LearningObjective.find(params[:id])
    @learning_objective.destroy
    redirect_to student_competency_learning_objectives_path, notice:
     'Leerdoel succesvol verwijderd'
  end

  private

  def learning_objective_params
    params.require(:learning_objective)
      .permit(:name, :competency_id, :academic_year, :period)
  end
end

app/controllers/student/proofs_controller.rb
# class proof
class Student::ProofsController < ApplicationController
  def index
    @proofs = Activity.find(params[:activity_id]).proofs.all
  end

  def show
    @proof = Proof.find(params[:id])
  end

  def new
    @proof = Proof.new
  end

  def create
    @proof = Proof.new(proof_params)
    @proof.activity_id = params[:activity_id]

    if @proof.save
      redirect_to student_competency_learning_objective_activity_proofs_path, notice: 'Bewijs succesvol aangemaakt'

    else
      render 'new'
    end
  end

  def edit
    @proof = Proof.find(params[:id])
  end

  def update
    @proof = Proof.find(params[:id])

    if @proof.update(proof_params)

      redirect_to student_competency_learning_objective_activity_proofs_path, notice: 'Bewijs succesvol aangepast'

    else
      render 'edit'
    end
  end

  def destroy
    @proof = Proof.find(params[:id])
    @proof.destroy

    redirect_to student_competency_learning_objective_activity_proofs_path, notice: 'Bewijs succesvol verwijderd'
  end

  private

  def proof_params
    params.require(:proof).permit(:description, :activity_id, :reference)
  end
end

app/helpers/student/activities_helper.rb
# activity helper
module Student::ActivitiesHelper
end

app/helpers/student/competencies_helper.rb
# competency helper
module Student::CompetenciesHelper
end

app/helpers/student/contexts_helper.rb
# context helper
module Student::ContextsHelper
end

app/helpers/student/dashboard_helper.rb
# dashboard helper
module Student::DashboardHelper
end

app/helpers/student/learning_objectives_helper.rb
# learning objective helper
module Student::LearningObjectivesHelper
end

app/helpers/student/proofs_helper.rb
# proofs helper
module Student::ProofsHelper
end

app/views/student/proofs/edit.html.haml
#sections
  %h2 pas hier je bewijs aan

  = form_for @proof, url: student_competency_learning_objective_activity_proof_path do |pr|

    .dev
      = pr.label 'Pas hier de sectie van het document of bestand waar het bewijs valt te vinden aan'
      .sub
        = pr.text_area :description
    .dev
      = pr.label 'Pas hier de locatie waar het bestand of document te vinden valt aan'
      .sub
        = pr.text_area :reference

   
    .under
      = pr.submit 'Bevestig', :class => 'submit_button' 

  .under
    = link_to 'Terug naar al het bewijs', student_competency_learning_objective_activity_proofs_path

app/views/student/proofs/index.html.haml
#sections
  - @proofs.each do |pr|
    .overview 
      .overview_link
        = link_to pr.description, student_competency_learning_objective_activity_proof_path(params[:competency_id], params[:learning_objective_id], params[:activity_id], pr.id)

  .under
    = link_to 'Nieuw bewijs toevoegen', new_student_competency_learning_objective_activity_proof_path
    |
    = link_to 'Terug naar alle activteiten', student_competency_learning_objective_activities_path

app/views/student/proofs/new.html.haml
#sections
  %h2 Voeg bewijs toe aan je huidige activiteit

  = form_for @proof, url: student_competency_learning_objective_activity_proofs_path do |pr|

    .dev
      = pr.label 'In welke sectie van het document of bestand valt het bewijs te vindenn?'
      .sub
        = pr.text_area :description
    .dev
      = pr.label 'Waar valt dit document/bestand te vinden?'
      .sub
        = pr.text_area :reference

   
    .under
      = pr.submit 'Bevestig', :class => 'submit_button' 

  .under
    = link_to 'Terug naar al het bewijs', student_competency_learning_objective_activity_proofs_path

app/views/student/proofs/show.html.haml
#sections
  .overview
    .overview_link
      %h2 Sectie waar de bewijslast te vinden is:
      %p= @proof.description

      Link waar dit document of bestand te vinden valt:
      %p= link_to 'website', @proof.reference

      = link_to 'Aanpassen', edit_student_competency_learning_objective_activity_proof_path
      |
      = link_to 'Verwijderen', student_competency_learning_objective_activity_proof_path, method: :delete, data: { confirm: 'Weet je het zeker?' }